### ISSUE TITLE
Have all of the SSCR codes been uploaded yet?

### ISSUE THREAD

**Issue by lzlzlizi** [tsujuifu/pytorch_sscr#1]
Hi,

Thanks for sharing the codes and finishing the interesting work! 

I noticed there is only one script in `sscr/scripts` folder. Therefore, I am wondering, are the codes in that script enough for implementing the method? Or the codes for sscr are actually in the `geneva` folder?

Also, is there any pre-trained model?

Thanks!

**Comment by tsujuifu** [comment]
Hi lzlzlizi, 

please check the **Usage** and edit **geneva/inference/train.py** to train for different settings.
And the trained model is also provided [here](https://drive.google.com/drive/u/1/folders/1DvmEmqTaDjZA0Fea1MfW7A0Kz2fjf8g9).

**Comment by lzlzlizi** [comment]
Thanks for the reply!
It seems I have asked a stupid question...
