### ISSUE TITLE
inference/predict.py

### ISSUE THREAD

**Issue by Cm744** [tsujuifu/pytorch_sscr#4]
Hi could you please provide scripts for the inference? just upload any image with an appropriate customized guidance sentence, and then see the results.

**Comment by tsujuifu** [comment]
We use the following command to do inference:
```
python -m geneva.inference.test @example_args/iclevr-d-subtract.args
```
Please edit **example_args/iclevr-d-subtract.args** for your own setting.
I will try to make an independent **predict.py**, but being busy these days with my submission 🥲.
